export const ApiCatalogo = [
  {
    id: 1,
    icono: "water",
    colorIcono: "colorWater",
    curso: "Curso 1",
    ciclo: 7,
    nivel: ["Básico", "Medio", "Avanzado"],
    duracion: "3 sem.",
    colegio: "Nombre 1",
    universidad: "Nombre 1",
  },
  {
    id: 2,
    icono: "computer",
    colorIcono: "colorComputer",
    curso: "Curso 2",
    ciclo: 7,
    nivel: ["Básico", "Medio", "Avanzado"],
    duracion: "4 sem.",
    colegio: "Nombre 1",
    universidad: "Nombre 1",
  },
  {
    id: 3,
    icono: "cuadricula",
    colorIcono: "colorCuadricula",
    curso: "Curso 3",
    ciclo: 7,
    nivel: ["Básico", "Medio", "Avanzado"],
    duracion: "5 sem.",
    colegio: "Nombre 1",
    universidad: "Nombre 1",
  },
  {
    id: 4,
    icono: "cuadricula",
    colorIcono: "colorCuadricula",
    curso: "Curso 4",
    ciclo: 7,
    nivel: ["Básico", "Medio", "Avanzado"],
    duracion: "6 sem.",
    colegio: "Nombre 1",
    universidad: "Nombre 1",
  },
];

export const ApiCiclo = [
    {
        id: 1,
        nombre: "Ciclo 1",
        fechaInicio: "24",
        mesInicio: "Mayo",
        estado: "Inactivo",
        process: 0,
    },
    {
        id: 2,
        nombre: "Ciclo 2",
        fechaInicio: "04",
        mesInicio: "Abril",
        estado: "Activo",
        process: 25,
    },
    {
        id: 3,
        nombre: "Ciclo 3",
        fechaInicio: "17",
        mesInicio: "Marzo",
        estado: "Activo",
        process: 50,
    }
];
