export const ApiCatalogo = [
    {
        id: 1,
        icono: "water",
        colorIcono: "colorWater",
        curso: "Curso 1",
        ciclo: 7,
        nivel: ["Básico", "Medio", "Avanzado"],
        duracion: "3 sem.",
        colegio: "Nombre 1",
        universidad: "Nombre 1",
    },
    {
        id: 2,
        icono: "computer",
        colorIcono: "colorComputer",
        curso: "Curso 2",
        ciclo: 7,
        nivel: ["Básico", "Medio", "Avanzado"],
        duracion: "4 sem.",
        colegio: "Nombre 1",
        universidad: "Nombre 1",
    },
    {
        id: 3,
        icono: "cuadricula",
        colorIcono: "colorCuadricula",
        curso: "Curso 3",
        ciclo: 7,
        nivel: ["Básico", "Medio", "Avanzado"],
        duracion: "5 sem.",
        colegio: "Nombre 1",
        universidad: "Nombre 1",
    },
    {
        id: 4,
        icono: "cuadricula",
        colorIcono: "colorCuadricula",
        curso: "Curso 4",
        ciclo: 7,
        nivel: ["Básico", "Medio", "Avanzado"],
        duracion: "6 sem.",
        colegio: "Nombre 1",
        universidad: "Nombre 1",
    },
]